CREATE TABLE IF NOT EXISTS students(
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(150) NOT NULL,
    dateOfBirth VARCHAR(10) NOT NULL,
    studentClass VARCHAR(50) NOT NULL,
    courseType VARCHAR(100) NOT NULL,
    carometer VARCHAR(500) NOT NULL,
    aapmStatus BOOLEAN NOT NULL,
    internshipStatus BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS lockers(
id SERIAL PRIMARY KEY UNIQUE NOT NULL,
occupationStatus BOOLEAN NOT NULL,
owner VARCHAR(150) NOT NULL
);